Repository LiskHQ/lisk-nano, pull requests merged in 2018-05, with the labels that each got.

#1060 Update Jenkinsfile for slack integration
  Jenkinsfile
Labels: ready

#1064 Keep selected network option when creating new ID - Closes #1031
  src/components/login/login.js
Labels: pending review

#1069 Add support for optional data field - Closes #595
  i18n/locales/en/common.json
  src/actions/account.js
  src/components/send/send.css
  src/components/send/send.js
  src/components/send/send.test.js
  src/utils/api/account.js
Labels: :eye: pending review

#1068 Remove error toast after autoupdate - Closes #1062
  src/utils/externalLinks.js
Labels: :eye: pending review

#1075 Replace lisk-js with lisk-elements - Closes #1067
  package.json
  src/actions/peers.js
  src/actions/peers.test.js
  src/components/decryptMessage/decryptMessage.js
  src/components/decryptMessage/decryptMessage.test.js
  src/components/encryptMessage/encryptMessage.js
  src/components/encryptMessage/encryptMessage.test.js
  src/components/login/login.test.js
  src/components/registerDelegate/registerDelegate.test.js
  src/components/signMessage/signMessage.js
  src/components/verifyMessage/index.js
  src/components/voting/index.test.js
  src/store/middlewares/login.test.js
  src/store/reducers/peers.js
  src/utils/api/account.js
  src/utils/api/delegate.js
  src/utils/api/delegate.test.js
  src/utils/api/forging.test.js
  test/integration/voteDialog/index.test.js
Labels: :eye: pending review

#1071 Disallow lowercase l in address - Closes #1070
  src/components/send/send.js
  src/utils/api/account.js
  src/utils/api/delegate.js
Labels: :eye: pending review

#1074 Fix autocomplete when changing a vote - Closes #990
  src/utils/api/delegate.js
Labels: :eye: pending review

#1073 Re-enable unit tests after Core 1.0.0 migration - #1072
  src/actions/peers.js
  src/actions/peers.test.js
  src/constants/netHashes.js
  src/store/middlewares/login.test.js
  src/utils/api/account.test.js
Labels: :eye: pending review
